# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import escalation_pb2 as escalation__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in escalation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EscalationSagaStub:
    """EscalationSaga is an explicit state machine for handing browser control
    between the agent and a human operator:
    AGENT_CONTROLLED -> INTERVENTION_REQUESTED -> HUMAN_CONTROLLED
    -> CONTROL_RETURNED -> (resume | terminate)
    A dead-lettered hard failure from replay_runtime is what drives the first
    transition; a human claiming the live session drives the second.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestIntervention = channel.unary_unary(
                '/trailmarked.escalation.EscalationSaga/RequestIntervention',
                request_serializer=escalation__pb2.InterventionRequest.SerializeToString,
                response_deserializer=escalation__pb2.InterventionAck.FromString,
                _registered_method=True)
        self.ClaimSession = channel.unary_unary(
                '/trailmarked.escalation.EscalationSaga/ClaimSession',
                request_serializer=escalation__pb2.ClaimRequest.SerializeToString,
                response_deserializer=escalation__pb2.ClaimAck.FromString,
                _registered_method=True)
        self.RecordHumanAction = channel.unary_unary(
                '/trailmarked.escalation.EscalationSaga/RecordHumanAction',
                request_serializer=escalation__pb2.HumanActionRequest.SerializeToString,
                response_deserializer=escalation__pb2.Ack.FromString,
                _registered_method=True)
        self.ReleaseControl = channel.unary_unary(
                '/trailmarked.escalation.EscalationSaga/ReleaseControl',
                request_serializer=escalation__pb2.ReleaseRequest.SerializeToString,
                response_deserializer=escalation__pb2.ReleaseAck.FromString,
                _registered_method=True)
        self.GetSagaState = channel.unary_unary(
                '/trailmarked.escalation.EscalationSaga/GetSagaState',
                request_serializer=escalation__pb2.SagaStateRequest.SerializeToString,
                response_deserializer=escalation__pb2.SagaState.FromString,
                _registered_method=True)
        self.ListSagas = channel.unary_unary(
                '/trailmarked.escalation.EscalationSaga/ListSagas',
                request_serializer=escalation__pb2.ListSagasRequest.SerializeToString,
                response_deserializer=escalation__pb2.ListSagasResponse.FromString,
                _registered_method=True)


class EscalationSagaServicer:
    """EscalationSaga is an explicit state machine for handing browser control
    between the agent and a human operator:
    AGENT_CONTROLLED -> INTERVENTION_REQUESTED -> HUMAN_CONTROLLED
    -> CONTROL_RETURNED -> (resume | terminate)
    A dead-lettered hard failure from replay_runtime is what drives the first
    transition; a human claiming the live session drives the second.
    """

    def RequestIntervention(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordHumanAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSagaState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSagas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EscalationSagaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestIntervention': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestIntervention,
                    request_deserializer=escalation__pb2.InterventionRequest.FromString,
                    response_serializer=escalation__pb2.InterventionAck.SerializeToString,
            ),
            'ClaimSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimSession,
                    request_deserializer=escalation__pb2.ClaimRequest.FromString,
                    response_serializer=escalation__pb2.ClaimAck.SerializeToString,
            ),
            'RecordHumanAction': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordHumanAction,
                    request_deserializer=escalation__pb2.HumanActionRequest.FromString,
                    response_serializer=escalation__pb2.Ack.SerializeToString,
            ),
            'ReleaseControl': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseControl,
                    request_deserializer=escalation__pb2.ReleaseRequest.FromString,
                    response_serializer=escalation__pb2.ReleaseAck.SerializeToString,
            ),
            'GetSagaState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSagaState,
                    request_deserializer=escalation__pb2.SagaStateRequest.FromString,
                    response_serializer=escalation__pb2.SagaState.SerializeToString,
            ),
            'ListSagas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSagas,
                    request_deserializer=escalation__pb2.ListSagasRequest.FromString,
                    response_serializer=escalation__pb2.ListSagasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trailmarked.escalation.EscalationSaga', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trailmarked.escalation.EscalationSaga', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EscalationSaga:
    """EscalationSaga is an explicit state machine for handing browser control
    between the agent and a human operator:
    AGENT_CONTROLLED -> INTERVENTION_REQUESTED -> HUMAN_CONTROLLED
    -> CONTROL_RETURNED -> (resume | terminate)
    A dead-lettered hard failure from replay_runtime is what drives the first
    transition; a human claiming the live session drives the second.
    """

    @staticmethod
    def RequestIntervention(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.escalation.EscalationSaga/RequestIntervention',
            escalation__pb2.InterventionRequest.SerializeToString,
            escalation__pb2.InterventionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.escalation.EscalationSaga/ClaimSession',
            escalation__pb2.ClaimRequest.SerializeToString,
            escalation__pb2.ClaimAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordHumanAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.escalation.EscalationSaga/RecordHumanAction',
            escalation__pb2.HumanActionRequest.SerializeToString,
            escalation__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.escalation.EscalationSaga/ReleaseControl',
            escalation__pb2.ReleaseRequest.SerializeToString,
            escalation__pb2.ReleaseAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSagaState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.escalation.EscalationSaga/GetSagaState',
            escalation__pb2.SagaStateRequest.SerializeToString,
            escalation__pb2.SagaState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSagas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.escalation.EscalationSaga/ListSagas',
            escalation__pb2.ListSagasRequest.SerializeToString,
            escalation__pb2.ListSagasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
