# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import event_log_pb2 as event__log__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in event_log_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventLogStub:
    """EventLog is the single write side of the platform. Every domain event
    (ObservationCaptured, ActionDecided, ActionExecuted, StepSucceeded,
    RunSucceeded/Failed, ReplayRequested, InterventionRequested, ...) is
    appended here through the outbox dispatcher, never written directly by
    a producing service's own transaction.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Append = channel.unary_unary(
                '/trailmarked.eventlog.EventLog/Append',
                request_serializer=event__log__pb2.AppendRequest.SerializeToString,
                response_deserializer=event__log__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.Fetch = channel.unary_unary(
                '/trailmarked.eventlog.EventLog/Fetch',
                request_serializer=event__log__pb2.FetchRequest.SerializeToString,
                response_deserializer=event__log__pb2.FetchResponse.FromString,
                _registered_method=True)
        self.CommitOffset = channel.unary_unary(
                '/trailmarked.eventlog.EventLog/CommitOffset',
                request_serializer=event__log__pb2.CommitOffsetRequest.SerializeToString,
                response_deserializer=event__log__pb2.CommitOffsetResponse.FromString,
                _registered_method=True)
        self.StreamTopic = channel.unary_stream(
                '/trailmarked.eventlog.EventLog/StreamTopic',
                request_serializer=event__log__pb2.StreamTopicRequest.SerializeToString,
                response_deserializer=event__log__pb2.Event.FromString,
                _registered_method=True)
        self.DeadLetter = channel.unary_unary(
                '/trailmarked.eventlog.EventLog/DeadLetter',
                request_serializer=event__log__pb2.DeadLetterRequest.SerializeToString,
                response_deserializer=event__log__pb2.DeadLetterResponse.FromString,
                _registered_method=True)


class EventLogServicer:
    """EventLog is the single write side of the platform. Every domain event
    (ObservationCaptured, ActionDecided, ActionExecuted, StepSucceeded,
    RunSucceeded/Failed, ReplayRequested, InterventionRequested, ...) is
    appended here through the outbox dispatcher, never written directly by
    a producing service's own transaction.
    """

    def Append(self, request, context):
        """Append is only ever called by an outbox dispatcher, never directly by
        business logic, so a crash between the local write and the publish
        can't silently drop an event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fetch(self, request, context):
        """Fetch lets a consumer group pull a bounded batch starting at its last
        committed offset for a topic.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitOffset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTopic(self, request, context):
        """StreamTopic is a server-streaming tail of a topic from a given offset,
        used by the dashboard's SSE bridge and by long-lived consumers
        (registry projector, replay runtime, escalation saga).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeadLetter(self, request, context):
        """Publishes a poison-pilled event to a topic's dead-letter counterpart
        with the failure context attached.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventLogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=event__log__pb2.AppendRequest.FromString,
                    response_serializer=event__log__pb2.AppendResponse.SerializeToString,
            ),
            'Fetch': grpc.unary_unary_rpc_method_handler(
                    servicer.Fetch,
                    request_deserializer=event__log__pb2.FetchRequest.FromString,
                    response_serializer=event__log__pb2.FetchResponse.SerializeToString,
            ),
            'CommitOffset': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitOffset,
                    request_deserializer=event__log__pb2.CommitOffsetRequest.FromString,
                    response_serializer=event__log__pb2.CommitOffsetResponse.SerializeToString,
            ),
            'StreamTopic': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTopic,
                    request_deserializer=event__log__pb2.StreamTopicRequest.FromString,
                    response_serializer=event__log__pb2.Event.SerializeToString,
            ),
            'DeadLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.DeadLetter,
                    request_deserializer=event__log__pb2.DeadLetterRequest.FromString,
                    response_serializer=event__log__pb2.DeadLetterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trailmarked.eventlog.EventLog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trailmarked.eventlog.EventLog', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventLog:
    """EventLog is the single write side of the platform. Every domain event
    (ObservationCaptured, ActionDecided, ActionExecuted, StepSucceeded,
    RunSucceeded/Failed, ReplayRequested, InterventionRequested, ...) is
    appended here through the outbox dispatcher, never written directly by
    a producing service's own transaction.
    """

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.eventlog.EventLog/Append',
            event__log__pb2.AppendRequest.SerializeToString,
            event__log__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.eventlog.EventLog/Fetch',
            event__log__pb2.FetchRequest.SerializeToString,
            event__log__pb2.FetchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitOffset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.eventlog.EventLog/CommitOffset',
            event__log__pb2.CommitOffsetRequest.SerializeToString,
            event__log__pb2.CommitOffsetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/trailmarked.eventlog.EventLog/StreamTopic',
            event__log__pb2.StreamTopicRequest.SerializeToString,
            event__log__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeadLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.eventlog.EventLog/DeadLetter',
            event__log__pb2.DeadLetterRequest.SerializeToString,
            event__log__pb2.DeadLetterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
