# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import registry_pb2 as registry__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in registry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CapabilityRegistryStub:
    """CapabilityRegistry is the read side (CQRS) projected from the event log,
    plus the compiler that folds a successful discovery run into a versioned
    capability contract. Internal callers (discovery_plane on RunSucceeded,
    replay_runtime before executing) reach it here over gRPC; the REST and
    GraphQL surfaces in this same process are for agents and the dashboard.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CompileCapability = channel.unary_unary(
                '/trailmarked.registry.CapabilityRegistry/CompileCapability',
                request_serializer=registry__pb2.CompileRequest.SerializeToString,
                response_deserializer=registry__pb2.CompileResponse.FromString,
                _registered_method=True)
        self.GetCapability = channel.unary_unary(
                '/trailmarked.registry.CapabilityRegistry/GetCapability',
                request_serializer=registry__pb2.GetCapabilityRequest.SerializeToString,
                response_deserializer=registry__pb2.Capability.FromString,
                _registered_method=True)
        self.ResolveForTenant = channel.unary_unary(
                '/trailmarked.registry.CapabilityRegistry/ResolveForTenant',
                request_serializer=registry__pb2.ResolveRequest.SerializeToString,
                response_deserializer=registry__pb2.Capability.FromString,
                _registered_method=True)
        self.ListCapabilities = channel.unary_unary(
                '/trailmarked.registry.CapabilityRegistry/ListCapabilities',
                request_serializer=registry__pb2.ListRequest.SerializeToString,
                response_deserializer=registry__pb2.ListResponse.FromString,
                _registered_method=True)
        self.GetVersionHistory = channel.unary_unary(
                '/trailmarked.registry.CapabilityRegistry/GetVersionHistory',
                request_serializer=registry__pb2.VersionHistoryRequest.SerializeToString,
                response_deserializer=registry__pb2.VersionHistoryResponse.FromString,
                _registered_method=True)


class CapabilityRegistryServicer:
    """CapabilityRegistry is the read side (CQRS) projected from the event log,
    plus the compiler that folds a successful discovery run into a versioned
    capability contract. Internal callers (discovery_plane on RunSucceeded,
    replay_runtime before executing) reach it here over gRPC; the REST and
    GraphQL surfaces in this same process are for agents and the dashboard.
    """

    def CompileCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveForTenant(self, request, context):
        """Merges a capability's base definition with a tenant's locator/param
        overlay at resolve time; the base is never mutated per tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CapabilityRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CompileCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.CompileCapability,
                    request_deserializer=registry__pb2.CompileRequest.FromString,
                    response_serializer=registry__pb2.CompileResponse.SerializeToString,
            ),
            'GetCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapability,
                    request_deserializer=registry__pb2.GetCapabilityRequest.FromString,
                    response_serializer=registry__pb2.Capability.SerializeToString,
            ),
            'ResolveForTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveForTenant,
                    request_deserializer=registry__pb2.ResolveRequest.FromString,
                    response_serializer=registry__pb2.Capability.SerializeToString,
            ),
            'ListCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCapabilities,
                    request_deserializer=registry__pb2.ListRequest.FromString,
                    response_serializer=registry__pb2.ListResponse.SerializeToString,
            ),
            'GetVersionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersionHistory,
                    request_deserializer=registry__pb2.VersionHistoryRequest.FromString,
                    response_serializer=registry__pb2.VersionHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trailmarked.registry.CapabilityRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trailmarked.registry.CapabilityRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CapabilityRegistry:
    """CapabilityRegistry is the read side (CQRS) projected from the event log,
    plus the compiler that folds a successful discovery run into a versioned
    capability contract. Internal callers (discovery_plane on RunSucceeded,
    replay_runtime before executing) reach it here over gRPC; the REST and
    GraphQL surfaces in this same process are for agents and the dashboard.
    """

    @staticmethod
    def CompileCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.registry.CapabilityRegistry/CompileCapability',
            registry__pb2.CompileRequest.SerializeToString,
            registry__pb2.CompileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.registry.CapabilityRegistry/GetCapability',
            registry__pb2.GetCapabilityRequest.SerializeToString,
            registry__pb2.Capability.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveForTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.registry.CapabilityRegistry/ResolveForTenant',
            registry__pb2.ResolveRequest.SerializeToString,
            registry__pb2.Capability.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.registry.CapabilityRegistry/ListCapabilities',
            registry__pb2.ListRequest.SerializeToString,
            registry__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.registry.CapabilityRegistry/GetVersionHistory',
            registry__pb2.VersionHistoryRequest.SerializeToString,
            registry__pb2.VersionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
