# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import replay_pb2 as replay__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in replay_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplayRuntimeStub:
    """ReplayRuntime executes a compiled capability deterministically. No LLM
    call ever happens on this path — that is the entire point of trailmarking
    a run. Idempotency-key checks and the circuit breaker live here.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitReplay = channel.unary_unary(
                '/trailmarked.replay.ReplayRuntime/SubmitReplay',
                request_serializer=replay__pb2.ReplayRequest.SerializeToString,
                response_deserializer=replay__pb2.ReplayAck.FromString,
                _registered_method=True)
        self.GetReplayStatus = channel.unary_unary(
                '/trailmarked.replay.ReplayRuntime/GetReplayStatus',
                request_serializer=replay__pb2.ReplayStatusRequest.SerializeToString,
                response_deserializer=replay__pb2.ReplayStatus.FromString,
                _registered_method=True)
        self.GetCircuitBreakerState = channel.unary_unary(
                '/trailmarked.replay.ReplayRuntime/GetCircuitBreakerState',
                request_serializer=replay__pb2.CircuitBreakerRequest.SerializeToString,
                response_deserializer=replay__pb2.CircuitBreakerState.FromString,
                _registered_method=True)
        self.ActOnLiveSession = channel.unary_unary(
                '/trailmarked.replay.ReplayRuntime/ActOnLiveSession',
                request_serializer=replay__pb2.ActOnLiveSessionRequest.SerializeToString,
                response_deserializer=replay__pb2.Ack.FromString,
                _registered_method=True)
        self.ReleaseLiveSession = channel.unary_unary(
                '/trailmarked.replay.ReplayRuntime/ReleaseLiveSession',
                request_serializer=replay__pb2.ReleaseLiveSessionRequest.SerializeToString,
                response_deserializer=replay__pb2.Ack.FromString,
                _registered_method=True)


class ReplayRuntimeServicer:
    """ReplayRuntime executes a compiled capability deterministically. No LLM
    call ever happens on this path — that is the entire point of trailmarking
    a run. Idempotency-key checks and the circuit breaker live here.
    """

    def SubmitReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplayStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCircuitBreakerState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActOnLiveSession(self, request, context):
        """A hard-failed run's browser session is kept alive (not closed) pending
        an escalation decision. These two RPCs let the escalation saga act on
        that SAME session from its own process, rather than a fresh one.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLiveSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplayRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitReplay,
                    request_deserializer=replay__pb2.ReplayRequest.FromString,
                    response_serializer=replay__pb2.ReplayAck.SerializeToString,
            ),
            'GetReplayStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplayStatus,
                    request_deserializer=replay__pb2.ReplayStatusRequest.FromString,
                    response_serializer=replay__pb2.ReplayStatus.SerializeToString,
            ),
            'GetCircuitBreakerState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCircuitBreakerState,
                    request_deserializer=replay__pb2.CircuitBreakerRequest.FromString,
                    response_serializer=replay__pb2.CircuitBreakerState.SerializeToString,
            ),
            'ActOnLiveSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ActOnLiveSession,
                    request_deserializer=replay__pb2.ActOnLiveSessionRequest.FromString,
                    response_serializer=replay__pb2.Ack.SerializeToString,
            ),
            'ReleaseLiveSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLiveSession,
                    request_deserializer=replay__pb2.ReleaseLiveSessionRequest.FromString,
                    response_serializer=replay__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trailmarked.replay.ReplayRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trailmarked.replay.ReplayRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplayRuntime:
    """ReplayRuntime executes a compiled capability deterministically. No LLM
    call ever happens on this path — that is the entire point of trailmarking
    a run. Idempotency-key checks and the circuit breaker live here.
    """

    @staticmethod
    def SubmitReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.replay.ReplayRuntime/SubmitReplay',
            replay__pb2.ReplayRequest.SerializeToString,
            replay__pb2.ReplayAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReplayStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.replay.ReplayRuntime/GetReplayStatus',
            replay__pb2.ReplayStatusRequest.SerializeToString,
            replay__pb2.ReplayStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCircuitBreakerState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.replay.ReplayRuntime/GetCircuitBreakerState',
            replay__pb2.CircuitBreakerRequest.SerializeToString,
            replay__pb2.CircuitBreakerState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActOnLiveSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.replay.ReplayRuntime/ActOnLiveSession',
            replay__pb2.ActOnLiveSessionRequest.SerializeToString,
            replay__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLiveSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trailmarked.replay.ReplayRuntime/ReleaseLiveSession',
            replay__pb2.ReleaseLiveSessionRequest.SerializeToString,
            replay__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
